import type { Product, User, Booking } from './types'

export const mockProducts: Product[] = [
  {
    id: 'p1',
    vendorId: 'v1',
    vendorName: 'TechEquip GmbH',
    title: 'LED Digital Display Board 6m²',
    description: 'High-brightness outdoor LED display board, ideal for events, trade fairs, and exhibitions. 6m² viewing area with full HD resolution. Easy setup with included mounting kit.',
    category: 'Display & Visual',
    pricePerDay: 380,
    minRentalDays: 1,
    location: 'Hamburg, Germany',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80',
    ],
    status: 'active',
    available: true,
    specifications: {
      'Resolution': '1920 x 1080 (Full HD)',
      'Brightness': '5000 cd/m²',
      'Size': '3m × 2m',
      'Weight': '85 kg',
      'Power': '2.4 kW',
    },
    createdAt: '2024-01-10',
  },
  {
    id: 'p2',
    vendorId: 'v1',
    vendorName: 'TechEquip GmbH',
    title: 'Industrial Generator 50kVA',
    description: 'Diesel-powered industrial generator, suitable for construction sites, outdoor events, and emergency power backup. Includes automatic voltage regulation and noise insulation housing.',
    category: 'Power & Energy',
    pricePerDay: 250,
    minRentalDays: 2,
    location: 'Hamburg, Germany',
    images: [
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80',
    ],
    status: 'active',
    available: true,
    specifications: {
      'Power Output': '50 kVA / 40 kW',
      'Fuel Type': 'Diesel',
      'Tank Capacity': '200 L',
      'Runtime': '~20 hours',
      'Noise Level': '68 dB(A)',
    },
    createdAt: '2024-01-15',
  },
  {
    id: 'p3',
    vendorId: 'v2',
    vendorName: 'HeavyLift Solutions',
    title: 'Electric Forklift 3.5T',
    description: 'Zero-emission electric forklift with 3500 kg lifting capacity. Perfect for warehouse operations, logistics centres, and indoor use. Certified operator training available on request.',
    category: 'Material Handling',
    pricePerDay: 195,
    minRentalDays: 1,
    location: 'Berlin, Germany',
    images: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    ],
    status: 'active',
    available: true,
    specifications: {
      'Lift Capacity': '3,500 kg',
      'Lift Height': '5.5 m',
      'Drive': 'Electric (48V)',
      'Battery Life': '8 hours',
      'Width': '1.2 m',
    },
    createdAt: '2024-02-01',
  },
  {
    id: 'p4',
    vendorId: 'v2',
    vendorName: 'HeavyLift Solutions',
    title: 'Mobile Scissor Lift 12m',
    description: 'Self-propelled electric scissor lift reaching 12m working height. Ideal for interior construction, maintenance, and installation work. Non-marking tyres for sensitive floors.',
    category: 'Access Equipment',
    pricePerDay: 165,
    minRentalDays: 1,
    location: 'Munich, Germany',
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
    ],
    status: 'active',
    available: false,
    specifications: {
      'Working Height': '12 m',
      'Platform Size': '2.3m × 1.2m',
      'Load Capacity': '450 kg',
      'Drive': 'Electric',
      'Certification': 'EN 280',
    },
    createdAt: '2024-02-10',
  },
  {
    id: 'p5',
    vendorId: 'v3',
    vendorName: 'AV Pro Rentals',
    title: 'Professional Sound System 10kW',
    description: 'Complete PA system with line arrays, subwoofers, and mixing console. Supports audiences up to 2000 people. Perfect for corporate events, product launches, and outdoor festivals.',
    category: 'Audio & Visual',
    pricePerDay: 420,
    minRentalDays: 1,
    location: 'Frankfurt, Germany',
    images: [
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    ],
    status: 'active',
    available: true,
    specifications: {
      'Output Power': '10,000 W RMS',
      'Speakers': '8× Line Array + 4× Subwoofer',
      'Coverage': 'Up to 2,000 persons',
      'Console': '32-channel digital mixer',
      'Setup Time': '3–4 hours',
    },
    createdAt: '2024-03-01',
  },
  {
    id: 'p6',
    vendorId: 'v3',
    vendorName: 'AV Pro Rentals',
    title: 'Conference Video System Pack',
    description: 'Complete conferencing setup with 85" 4K display, PTZ camera, wireless microphones, and AV receiver. Plug-and-play for boardrooms and hybrid events.',
    category: 'Display & Visual',
    pricePerDay: 290,
    minRentalDays: 1,
    location: 'Frankfurt, Germany',
    images: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    ],
    status: 'active',
    available: true,
    specifications: {
      'Display': '85" 4K UHD',
      'Camera': 'PTZ 4K, 12× optical zoom',
      'Microphones': '4× wireless lapel + 2× handheld',
      'Connectivity': 'HDMI, USB-C, Wi-Fi',
      'Setup Time': '1 hour',
    },
    createdAt: '2024-03-05',
  },
]

export const mockVendors: User[] = [
  {
    id: 'v1',
    name: 'Klaus Müller',
    email: 'k.mueller@techequip.de',
    role: 'vendor',
    company: 'TechEquip GmbH',
    phone: '+49 40 123456',
    verificationStatus: 'verified',
    createdAt: '2024-01-05',
    govtDocType: 'Gewerbeanmeldung',
    govtDocNumber: 'HRB 12345',
  },
  {
    id: 'v2',
    name: 'Anna Schmidt',
    email: 'a.schmidt@heavylift.de',
    role: 'vendor',
    company: 'HeavyLift Solutions',
    phone: '+49 30 654321',
    verificationStatus: 'verified',
    createdAt: '2024-01-20',
    govtDocType: 'Handelsregister',
    govtDocNumber: 'HRB 67890',
  },
  {
    id: 'v3',
    name: 'Markus Weber',
    email: 'm.weber@avpro.de',
    role: 'vendor',
    company: 'AV Pro Rentals',
    phone: '+49 69 111222',
    verificationStatus: 'pending',
    createdAt: '2024-03-01',
    govtDocType: 'Gewerbeschein',
    govtDocNumber: 'GS-2024-0312',
  },
]

export const mockRenters: User[] = [
  {
    id: 'r1',
    name: 'Sophie Bauer',
    email: 's.bauer@eventco.de',
    role: 'renter',
    company: 'EventCo GmbH',
    phone: '+49 40 999888',
    verificationStatus: 'verified',
    createdAt: '2024-02-01',
    govtDocType: 'Gewerbeanmeldung',
    govtDocNumber: 'HRB 99001',
  },
  {
    id: 'r2',
    name: 'Felix Hoffmann',
    email: 'f.hoffmann@bautech.de',
    role: 'renter',
    company: 'BauTech AG',
    phone: '+49 89 777666',
    verificationStatus: 'pending',
    createdAt: '2024-05-15',
    govtDocType: 'Handelsregister',
    govtDocNumber: 'HRB 55432',
  },
  {
    id: 'r3',
    name: 'Lena Fischer',
    email: 'l.fischer@logistics24.de',
    role: 'renter',
    company: 'Logistics24 GmbH',
    phone: '+49 211 334455',
    verificationStatus: 'rejected',
    createdAt: '2024-04-10',
    govtDocType: 'Gewerbeschein',
    govtDocNumber: 'GS-2024-0189',
  },
]

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    productId: 'p1',
    productTitle: 'LED Digital Display Board 6m²',
    renterId: 'r1',
    renterName: 'EventCo GmbH',
    vendorId: 'v1',
    startDate: '2024-06-10',
    endDate: '2024-06-12',
    totalDays: 3,
    totalAmount: 1140,
    status: 'confirmed',
    createdAt: '2024-06-01',
  },
  {
    id: 'b2',
    productId: 'p3',
    productTitle: 'Electric Forklift 3.5T',
    renterId: 'r1',
    renterName: 'EventCo GmbH',
    vendorId: 'v2',
    startDate: '2024-06-20',
    endDate: '2024-06-22',
    totalDays: 3,
    totalAmount: 585,
    status: 'pending',
    createdAt: '2024-06-05',
  },
]

export const categories = [
  'All Categories',
  'Display & Visual',
  'Power & Energy',
  'Material Handling',
  'Access Equipment',
  'Audio & Visual',
  'Construction',
  'Safety Equipment',
]

export const locations = [
  'All Locations',
  'Hamburg',
  'Berlin',
  'Munich',
  'Frankfurt',
  'Cologne',
  'Stuttgart',
]
